create or replace NONEDITIONABLE PACKAGE PKG_PHOTO AS 

  --리뷰사진 등록 프로시저
  PROCEDURE PROC_INS_PHOTO
  (
    IN_REVIEW_ID    IN VARCHAR2,
    IN_PHOTO_FILE   IN VARCHAR2,
    O_ERRCODE       OUT VARCHAR2,
    O_ERRMSG        OUT VARCHAR2
  );
  
  --리뷰사진 조회 프로시저
  PROCEDURE PROC_SEL_PHOTO
  (
    IN_PHOTO_ID     IN VARCHAR2,
    IN_REVIEW_ID    IN VARCHAR2,
    O_CUR           OUT SYS_REFCURSOR,
    O_ERRCODE       OUT VARCHAR2,
    O_ERRMSG        OUT VARCHAR2
  );
  
  --리뷰사진 수정 프로시저
  PROCEDURE PROC_UP_PHOTO
  (
    INS_PHOTO_ID IN VARCHAR2,
    INS_REVIEW_IDX IN INTEGER,
    INS_PHOTO_FILE IN VARCHAR2,
    O_ERRCODE OUT VARCHAR2,
    O_ERRMSG OUT VARCHAR2
  );
  
  --리뷰사진 삭제 프로시저
  PROCEDURE PROC_DEL_PHOTO
  (
    IN_PHOTO_ID     IN VARCHAR2,
    O_ERRCODE       OUT VARCHAR2,
    O_ERRMSG        OUT VARCHAR2
  );

END PKG_PHOTO;