create or replace NONEDITIONABLE PACKAGE BODY PKG_PHOTO AS

  --리뷰사진 등록 프로시저
  PROCEDURE PROC_INS_PHOTO
  (
    IN_REVIEW_ID    IN VARCHAR2,
    IN_PHOTO_FILE   IN VARCHAR2,
    O_ERRCODE       OUT VARCHAR2,
    O_ERRMSG        OUT VARCHAR2
  ) AS
  
    V_NEW_PHOTO_ID      CHAR(6);
    CNT_REVIEW_ID       NUMBER;
    
    REVIEW_ID_EXCEPT    EXCEPTION;
  
  BEGIN
    
    SELECT 'PH' || TO_CHAR(TO_NUMBER(SUBSTR(NVL(MAX(PHOTO_ID), 'PH0000'), 3, 4)) + 1, 'FM0000')
    INTO V_NEW_PHOTO_ID
    FROM REVIEW_PHOTO_TBL;
    
    INSERT INTO REVIEW_PHOTO_TBL(PHOTO_ID,REVIW_ID,FILE_NAME)
    VALUES(V_NEW_PHOTO_ID,IN_REVIEW_ID,IN_PHOTO_FILE);
    
    --리뷰ID가 존재하는지 확인
    SELECT COUNT(*)
    INTO CNT_REVIEW_ID
    FROM REVIEW_TBL
    WHERE REVIEW_ID = IN_REVIEW_ID;
    
    IF CNT_REVIEW_ID = 0 THEN
        RAISE REVIEW_ID_EXCEPT;
    END IF;
    
    EXCEPTION
    WHEN REVIEW_ID_EXCEPT THEN
    O_ERRCODE := 'ERR_NO_REVIEW_ID';
    O_ERRMSG := '리뷰에 해당 리뷰ID가 존재하지 않습니다';
    ROLLBACK;
    
    WHEN OTHERS THEN
    O_ERRCODE := SQLCODE;
    O_ERRMSG := SQLERRM;
    
  END PROC_INS_PHOTO;
  
  --리뷰사진 조회 프로시저
  PROCEDURE PROC_SEL_PHOTO
  (
    IN_PHOTO_ID     IN VARCHAR2,
    IN_REVIEW_ID    IN VARCHAR2,
    O_CUR           OUT SYS_REFCURSOR,
    O_ERRCODE       OUT VARCHAR2,
    O_ERRMSG        OUT VARCHAR2
  ) AS
  
  BEGIN
    
    OPEN O_CUR FOR
    SELECT *
    FROM REVIEW_PHOTO_TBL
    WHERE PHOTO_ID LIKE '%' || IN_PHOTO_ID || '%'
    AND REVIW_ID LIKE '%' || IN_REVIEW_ID || '%';
    
    EXCEPTION
    WHEN OTHERS THEN
    O_ERRCODE := SQLCODE;
    O_ERRMSG := SQLERRM;
    
  END PROC_SEL_PHOTO;
  
  --리뷰사진 수정 프로시저
  PROCEDURE PROC_UP_PHOTO
  (
    INS_PHOTO_ID IN VARCHAR2,
    INS_REVIEW_IDX IN INTEGER,
    INS_PHOTO_FILE IN VARCHAR2,
    O_ERRCODE OUT VARCHAR2,
    O_ERRMSG OUT VARCHAR2
  ) AS
  BEGIN
  UPDATE REVIEW_PHOTO_TBL SET PHOTO_ID=INS_PHOTO_ID, REVIW_ID=INS_REVIEW_IDX, FILE_NAME=INS_PHOTO_FILE WHERE PHOTO_ID=INS_PHOTO_ID;
  
  EXCEPTION WHEN OTHERS THEN
  O_ERRCODE:=SQLCODE;
  O_ERRMSG:=SQLERRM;
  END PROC_UP_PHOTO;
  
  --리뷰사진 삭제 프로시저
  PROCEDURE PROC_DEL_PHOTO
  (
    IN_PHOTO_ID     IN VARCHAR2,
    O_ERRCODE       OUT VARCHAR2,
    O_ERRMSG        OUT VARCHAR2
  ) AS
  BEGIN
    
    DELETE FROM REVIEW_PHOTO_TBL
    WHERE PHOTO_ID = IN_PHOTO_ID;
    
    EXCEPTION
    WHEN OTHERS THEN
    O_ERRCODE := SQLCODE;
    O_ERRMSG := SQLERRM;
    
  END PROC_DEL_PHOTO;

END PKG_PHOTO;