create or replace NONEDITIONABLE PACKAGE BODY PKG_DELIVERY_ORDER AS

  --배달오더 등록 프로시저
  PROCEDURE PROC_INS_DELIVERY_ORDER
  (
    IN_ORDER_ID         IN VARCHAR2,
    IN_DRIVER_ID        IN VARCHAR2,
    IN_ORDER_DATE       IN VARCHAR2,
    IN_EXPECT_PICKC_UP   IN VARCHAR2,
    O_ERRCODE           OUT VARCHAR2,
    O_ERRMSG            OUT VARCHAR2
  ) AS
  
    V_NEW_DELIVERY_IDX  NUMBER;
    CNT_ORDER_ID        NUMBER;
    CNT_DRIVER_ID       NUMBER;
    
    CHK_DELIVERY_FEE    NUMBER;
    
    NOT_DELIVERY_EXCEPT EXCEPTION;
    ORDER_ID_EXCEPT     EXCEPTION;
    DRIVER_ID_EXCEPT    EXCEPTION;
  
  BEGIN
    
    SELECT TO_NUMBER(NVL(MAX(DELIVERY_IDX), 0)) + 1
    INTO V_NEW_DELIVERY_IDX
    FROM DELIVERY_ORDER_TBL;
    
    --주문목록에 배달료가 산정되어 있는지
    SELECT DELIVERY_FEE
    INTO CHK_DELIVERY_FEE
    FROM ORDER_LIST_TBL
    WHERE ORDER_ID = IN_ORDER_ID;
    
    IF CHK_DELIVERY_FEE = 0 THEN   
        RAISE NOT_DELIVERY_EXCEPT;
    ELSE
        INSERT INTO DELIVERY_ORDER_TBL(DELIVERY_IDX,ORDER_ID,DRIVER_ID,ORDER_DATE,EXPECT_PICK_UP)
        VALUES(V_NEW_DELIVERY_IDX,IN_ORDER_ID,IN_DRIVER_ID,
                TO_DATE(IN_ORDER_DATE,'YYYY-MM-DD HH24:MI:SS'),TO_DATE(IN_EXPECT_PICKC_UP,'YYYY-MM-DD HH24:MI:SS'));
    END IF;
    
    --주문목록에 주문ID가 있는지 확인
    SELECT COUNT(*)
    INTO CNT_ORDER_ID
    FROM ORDER_LIST_TBL
    WHERE ORDER_ID = IN_ORDER_ID;
    
    --대리기사ID 있는지 확인
    SELECT COUNT(*)
    INTO CNT_DRIVER_ID
    FROM DRIVER_TBL
    WHERE DRIVER_ID = IN_DRIVER_ID;
    
    IF CNT_ORDER_ID = 0 THEN
        RAISE ORDER_ID_EXCEPT;
    ELSIF CNT_DRIVER_ID = 0 THEN
        RAISE DRIVER_ID_EXCEPT;
    END IF;
    
    EXCEPTION
    WHEN NOT_DELIVERY_EXCEPT THEN
    O_ERRCODE := 'ERR_NO_DELIVERY';
    O_ERRMSG := '해당 주문은 포장주문입니다';
    ROLLBACK;
    
    WHEN ORDER_ID_EXCEPT THEN
    O_ERRCODE := 'ERR_NO_ORDER_ID';
    O_ERRMSG := '주문목록에 해당 주문ID가 존재하지 않습니다';
    ROLLBACK;
    
    WHEN DRIVER_ID_EXCEPT THEN
    O_ERRCODE := 'ERR_NO_DELIVERY_ID';
    O_ERRMSG := '해당 배달기사ID가 존재하지 않습니다';
    ROLLBACK;
    
    WHEN OTHERS THEN
    O_ERRCODE := SQLCODE;
    O_ERRMSG := SQLERRM;
    
  END PROC_INS_DELIVERY_ORDER;
  
  --배달오더 조회 프로시저
  PROCEDURE PROC_SEL_DELIVERY_ORDER
  (
    IN_ORDER_ID         IN VARCHAR2,
    IN_DRIVER_ID        IN VARCHAR2,
    O_CUR               OUT SYS_REFCURSOR,
    O_ERRCODE           OUT VARCHAR2,
    O_ERRMSG            OUT VARCHAR2
  ) AS
  
  BEGIN
    
    OPEN O_CUR FOR
    SELECT * 
    FROM DELIVERY_ORDER_TBL
    WHERE ORDER_ID LIKE '%' || IN_ORDER_ID || '%'
    AND DRIVER_ID LIKE '%' || IN_DRIVER_ID || '%';
    
    EXCEPTION
    WHEN OTHERS THEN
    O_ERRCODE := SQLCODE;
    O_ERRMSG := SQLERRM;
    
  END PROC_SEL_DELIVERY_ORDER;
  
  --배달오더 수정 프로시저
  PROCEDURE PROC_UP_DELIVERY_ORDER
  (
    IN_ORDER_ID         IN VARCHAR2,
    IN_DRIVER_ID        IN VARCHAR2,
    IN_ORDER_DATE       IN VARCHAR2,
    IN_EXPECT_PICKC_UP  IN VARCHAR2,
    O_ERRCODE           OUT VARCHAR2,
    O_ERRMSG            OUT VARCHAR2
  ) AS
  
    CNT_ORDER_ID        NUMBER;
    CNT_DRIVER_ID       NUMBER;
  
    ORDER_ID_EXCEPT     EXCEPTION;
    DRIVER_ID_EXCEPT    EXCEPTION;
  
  BEGIN
    
    UPDATE DELIVERY_ORDER_TBL
    SET EXPECT_PICKC_UP = TO_DATE(IN_EXPECT_PICKC_UP, 'YYYY-MM-DD HH24:MI:SS'),
        DRIVER_ID = IN_DRIVER_ID,
        ORDER_DATE = IN_ORDER_DATE
    WHERE ORDER_ID = IN_ORDER_ID
    AND DRIVER_ID = IN_DRIVER_ID;
    
    /*
    --주문목록에 주문ID가 있는지 확인
    SELECT COUNT(*)
    INTO CNT_ORDER_ID
    FROM ORDER_LIST_TBL
    WHERE ORDER_ID = IN_ORDER_ID;
    
    --대리기사ID 있는지 확인
    SELECT COUNT(*)
    INTO CNT_DRIVER_ID
    FROM DRIVER_TBL
    WHERE DRIVER_ID = IN_DRIVER_ID;
    
    IF CNT_ORDER_ID = 0 THEN
        RAISE ORDER_ID_EXCEPT;
    ELSIF CNT_DRIVER_ID = 0 THEN
        RAISE DRIVER_ID_EXCEPT;
    END IF;
    
    EXCEPTION
    WHEN ORDER_ID_EXCEPT THEN
    O_ERRCODE := 'ERR_NO_ORDER_ID';
    O_ERRMSG := '주문목록에 해당 주문ID가 존재하지 않습니다';
    ROLLBACK;
    
    WHEN DRIVER_ID_EXCEPT THEN
    O_ERRCODE := 'ERR_NO_DELIVERY_ID';
    O_ERRMSG := '해당 배달기사ID가 존재하지 않습니다';
    ROLLBACK;
    */
    
    EXCEPTION
    WHEN OTHERS THEN
    O_ERRCODE := SQLCODE;
    O_ERRMSG := SQLERRM;
    
  END PROC_UP_DELIVERY_ORDER;
  
  --배달오더 삭제 프로시저
  PROCEDURE PROC_DEL_D_ORDER
  (
    INS_IDX IN VARCHAR2,
    O_ERRCODE OUT VARCHAR2,
    O_ERRMSG OUT VARCHAR2
  ) AS
  BEGIN
   DELETE DELIVERY_ORDER_TBL WHERE DELIVERY_IDX=INS_IDX;
   
   EXCEPTION WHEN OTHERS THEN
   O_ERRCODE:=SQLCODE;
   O_ERRMSG:=SQLERRM;
   
  END PROC_DEL_D_ORDER;

END PKG_DELIVERY_ORDER;