create or replace NONEDITIONABLE PACKAGE PKG_DELIVERY_ORDER AS 

  --배달오더 등록 프로시저
  PROCEDURE PROC_INS_DELIVERY_ORDER
  (
    IN_ORDER_ID         IN VARCHAR2,
    IN_DRIVER_ID        IN VARCHAR2,
    IN_ORDER_DATE       IN VARCHAR2,
    IN_EXPECT_PICKC_UP   IN VARCHAR2,
    O_ERRCODE           OUT VARCHAR2,
    O_ERRMSG            OUT VARCHAR2
  );
  
  --배달오더 조회 프로시저
  PROCEDURE PROC_SEL_DELIVERY_ORDER
  (
    IN_ORDER_ID         IN VARCHAR2,
    IN_DRIVER_ID        IN VARCHAR2,
    O_CUR               OUT SYS_REFCURSOR,
    O_ERRCODE           OUT VARCHAR2,
    O_ERRMSG            OUT VARCHAR2
  );
  
  --배달오더 수정 프로시저
  PROCEDURE PROC_UP_DELIVERY_ORDER
  (
    IN_ORDER_ID         IN VARCHAR2,
    IN_DRIVER_ID        IN VARCHAR2,
    IN_ORDER_DATE       IN VARCHAR2,
    IN_EXPECT_PICKC_UP   IN VARCHAR2,
    O_ERRCODE           OUT VARCHAR2,
    O_ERRMSG            OUT VARCHAR2
  );
  
  --배달오더 삭제 프로시저
  PROCEDURE PROC_DEL_D_ORDER
  (
    INS_IDX IN VARCHAR2,
    O_ERRCODE OUT VARCHAR2,
    O_ERRMSG OUT VARCHAR2
  );

END PKG_DELIVERY_ORDER;