create or replace NONEDITIONABLE PACKAGE PKG_POINT AS 

  --포인트 등록 프로시저
  PROCEDURE PROC_INS_POINT
  (
    IN_ORDER_ID     IN VARCHAR2,
    IN_POINT_COM_ID IN VARCHAR2,
    O_ERRCODE       OUT VARCHAR2,
    O_ERRMSG        OUT VARCHAR2
  );
  
  --포인트 조회 프로시저
  PROCEDURE PROC_SEL_POINT
  (
    IN_USER_ID      IN VARCHAR2,
    IN_ORDER_ID     IN VARCHAR2,
    O_CUR           OUT SYS_REFCURSOR,
    O_ERRCODE       OUT VARCHAR2,
    O_ERRMSG        OUT VARCHAR2
  );
  
  --포인트 수정 프로시저
  PROCEDURE PROC_UP_POINT
    (
        INS_IDX IN INTEGER,
        INS_USER_ID IN VARCHAR2,
        INS_ORDER_ID IN VARCHAR2,
        INS_POINT_COMID IN VARCHAR2,
        INS_SAVE_POINT IN VARCHAR2,
        O_ERRCODE OUT VARCHAR2,
        O_ERRMSG OUT VARCHAR2
    );

END PKG_POINT;