--포인트내역 테이블에서 포인트가 적립되면 사용자 테이블의 포인트 자동 업데이트
create or replace NONEDITIONABLE TRIGGER "TRG_UP_USER_FOR_INS_POINT" AFTER INSERT ON EARN_POINT_HISTORY_TBL 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
DECLARE

    V_USER_ID           CHAR(6);
    V_POINT_USE         CHAR(1);

BEGIN
  
    SELECT USER_ID
    INTO V_USER_ID
    FROM USER_TBL
    WHERE USER_ID = :NEW.USER_ID;
    
    SELECT USE_POINT
    INTO V_POINT_USE
    FROM ORDER_LIST_TBL
    WHERE ORDER_ID = :NEW.ORDER_ID;
    
    UPDATE USER_TBL
    SET USER_POINT = (USER_POINT + :NEW.EARN_POINT)
    WHERE USER_ID = V_USER_ID;
    
    
END;