--결제내역에서 포인트를 사용하면 사용자 테이블에서 포인트 자동으로 차감
create or replace NONEDITIONABLE TRIGGER "TRG_UP_USER_FOR_INS_PAYMENT_LIST" AFTER INSERT ON PAYMENT_HISTORY_TBL 
FOR EACH ROW
DECLARE

    V_USER_ID   CHAR(6);

BEGIN
  
  SELECT MAX(USER_ID)
  INTO V_USER_ID
  FROM ORDER_TBL
  WHERE ORDER_ID = :NEW.ORDER_ID;
  
  IF :NEW.PAY_COM_ID = 'COM003' THEN
      UPDATE USER_TBL
      SET USER_POINT = (USER_POINT - :NEW.FINAL_PRICE)
      WHERE USER_ID = V_USER_ID;
  END IF;
  
END;