--주문 테이블의 수량, 수령방법이 변경되면 주문목록 테이블의 배달료랑 총 금액 자동으로 변경
create or replace NONEDITIONABLE TRIGGER "TRG_UP_ORDER_LIST_FOR_UP_ORDER" AFTER UPDATE OF TAKE_OUT,QUANTITY ON ORDER_TBL 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
DECLARE

    V_NEW_MENU_PRICE    NUMBER;
    V_OLD_MENU_PRICE    NUMBER;
    V_DIS_PRICE         NUMBER;
    
BEGIN
  
    SELECT MENU_PRICE
    INTO V_NEW_MENU_PRICE
    FROM MENU_TBL
    WHERE MENU_ID = :NEW.MENU_ID
    AND STORE_ID = :NEW.STORE_ID;
    
    SELECT MENU_PRICE
    INTO V_OLD_MENU_PRICE
    FROM MENU_TBL
    WHERE MENU_ID = :OLD.MENU_ID
    AND STORE_ID = :OLD.STORE_ID;
    
    --변경금액 차액 계산
    IF (V_OLD_MENU_PRICE * :OLD.QUANTITY) > (V_NEW_MENU_PRICE * :NEW.QUANTITY)THEN
        V_DIS_PRICE := ((V_OLD_MENU_PRICE * :OLD.QUANTITY) - (V_NEW_MENU_PRICE * :NEW.QUANTITY)) * -1;
    ELSE
        V_DIS_PRICE := (V_NEW_MENU_PRICE * :NEW.QUANTITY) - (V_OLD_MENU_PRICE * :OLD.QUANTITY);
    END IF;
    
      --수령방법이 포장으로 변경되면
      IF :NEW.TAKE_OUT = 'O' THEN
          UPDATE ORDER_LIST_TBL
          SET TOTAL_PRICE = TOTAL_PRICE + V_DIS_PRICE, 
              DELIVERY_FEE = 0;
          
      --수령방법이 배달로 변경되면    
      ELSIF :NEW.TAKE_OUT = 'X' THEN
        UPDATE ORDER_LIST_TBL
        SET TOTAL_PRICE = TOTAL_PRICE + V_DIS_PRICE, 
            DELIVERY_FEE = 2000;
          
      END IF;


END;