create or replace NONEDITIONABLE PACKAGE BODY PKG_DRIVER AS

  --배달기사 등록 프로시저
  PROCEDURE PROC_INS_DRIVER
  (
    IN_DRIVER_NAME  IN VARCHAR2,
    IN_DRIVER_TEL   IN VARCHAR2,
    O_ERRCODE       OUT VARCHAR2,
    O_ERRMSG        OUT VARCHAR2
  ) 
  AS
  
    V_NEW_DRIVER_ID     CHAR(6);
  
  BEGIN
  
    SELECT 'DR' || TO_CHAR(TO_NUMBER(SUBSTR(NVL(MAX(DRIVER_ID), 'DR0000'), 3, 4) + 1), 'FM0000')
    INTO V_NEW_DRIVER_ID
    FROM DRIVER_TBL;
    
    INSERT INTO DRIVER_TBL(DRIVER_ID,DRIVER_NAME,DRIVER_TEL) VALUES(V_NEW_DRIVER_ID,IN_DRIVER_NAME,IN_DRIVER_TEL);
    
    EXCEPTION
    WHEN OTHERS THEN
    O_ERRCODE := SQLCODE;
    O_ERRMSG := SQLERRM;
    
  END PROC_INS_DRIVER;
  
  --배달기사 조회 프로시저
  PROCEDURE PROC_SEL_DRIVER
  (
    IN_DRIVER_ID    IN VARCHAR2,
    IN_DRIVER_NAME  IN VARCHAR2,
    O_CUR           OUT SYS_REFCURSOR,
    O_ERRCODE       OUT VARCHAR2,
    O_ERRMSG        OUT VARCHAR2
  )
  AS
  
  BEGIN
    
    OPEN O_CUR FOR
    SELECT * FROM DRIVER_TBL
    WHERE DRIVER_ID LIKE '%' || IN_DRIVER_ID || '%'
    AND DRIVER_NAME LIKE '%' || IN_DRIVER_NAME || '%'
    ;
    
    EXCEPTION
    WHEN OTHERS THEN
    O_ERRCODE := SQLCODE;
    O_ERRMSG := SQLERRM;
    
  END PROC_SEL_DRIVER;
  
  --배달기사 수정 프로시저
  PROCEDURE PROC_UP_DRIVER
  (
    IN_DRIVER_ID    IN VARCHAR2,
    IN_DRIVER_NAME  IN VARCHAR2,
    IN_DRIVER_TEL   IN VARCHAR2,
    O_ERRCODE       OUT VARCHAR2,
    O_ERRMSG        OUT VARCHAR2
  )
  AS
  
  BEGIN
    
    UPDATE DRIVER_TBL
    SET DRIVER_NAME = IN_DRIVER_NAME,
        DRIVER_TEL = IN_DRIVER_TEL
    WHERE DRIVER_ID = IN_DRIVER_ID
    ;
    
    EXCEPTION
    WHEN OTHERS THEN
    O_ERRCODE := SQLCODE;
    O_ERRMSG := SQLERRM;
    
  END PROC_UP_DRIVER;
  
  --배달기사 삭제 프로시저
  PROCEDURE PROC_DEL_DRIVER
  (
    IN_DRIVER_ID    IN VARCHAR2,
    O_ERRCODE      OUT VARCHAR2,
    O_ERRMSG       OUT VARCHAR2
  )
  AS
  
    CNT_DRIVER_ID           NUMBER;
    DRIVER_DEL_EXCEPTION    EXCEPTION;
  
  BEGIN
  
    SELECT COUNT(DRIVER_ID)
    INTO CNT_DRIVER_ID
    FROM DRIVER_TBL
    WHERE DRIVER_ID = IN_DRIVER_ID;
    
    IF CNT_DRIVER_ID = 0 THEN
        RAISE DRIVER_DEL_EXCEPTION;
    END IF;
    
    DELETE FROM DRIVER_TBL
    WHERE DRIVER_ID = IN_DRIVER_ID;
    
    EXCEPTION
    WHEN DRIVER_DEL_EXCEPTION THEN
    O_ERRCODE := 'ERR-NODRID';
    O_ERRMSG := '기사 아이디가 존재하지 않습니다.';
    ROLLBACK;
   
    WHEN OTHERS THEN
    O_ERRCODE := SQLCODE;
    O_ERRMSG := SQLERRM;
    
  END PROC_DEL_DRIVER;

END PKG_DRIVER;